# Generated by Django 2.1.7 on 2019-03-22 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djangosaml2idp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreementrecord',
            name='date',
        ),
        migrations.AddField(
            model_name='agreementrecord',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agreementrecord',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
