# Generated by Django 2.2.10 on 2020-04-05 17:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('djangosaml2idp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persistentid',
            name='persistent_id',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='User Persistent Id for this SP'),
        ),
    ]
