# Generated by Django 3.0.5 on 2020-05-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosaml2idp', '0002_persistent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='cache_expiration_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cache metadata until'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='metadata_expiration_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Metadata valid until'),
        ),
    ]
