# Generated by Django 2.2.10 on 2020-04-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosaml2idp', '0002_change_persistent_id_to_uuid_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='persistentid',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='persistentid',
            constraint=models.UniqueConstraint(fields=('sp', 'persistent_id'), name='unique_ids_per_sp'),
        ),
        migrations.AddConstraint(
            model_name='persistentid',
            constraint=models.UniqueConstraint(fields=('sp', 'user'), name='unique_users_per_sp'),
        ),
    ]
