# Generated by Django 2.0.13 on 2019-03-27 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosaml2idp', '0003_auto_20190327_1445'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agreementrecord',
            unique_together=set(),
        ),
    ]
