# Generated by Django 2.0.13 on 2019-03-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosaml2idp', '0004_auto_20190327_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreementrecord',
            name='sp_entity_id',
            field=models.TextField(),
        ),
    ]
